import PanelHeading from '../layout/PanelHeading'

function ServicesView({ services }) {
    const total = services.reduce((sum, service) => sum + Number(service.total_asistencias || 0), 0) || 1
    return <><section className="service-summary">{services.map((service) => <ServiceCard service={service} share={Math.round((Number(service.total_asistencias || 0) / total) * 100)} key={service.servicio} />)}</section><section className="panel service-analysis"><PanelHeading title="Uso por departamento" subtitle="Detecta si la prestación está concentrada en ciertas áreas" /><div className="service-columns">{services.map((service) => <article className="service-column" key={service.servicio}><div className="service-column-heading"><span className={`service-mark ${service.servicio === 'Masaje' ? 'massage' : 'physio'}`}>{service.servicio === 'Masaje' ? '✦' : '✚'}</span><div><h3>{service.servicio}</h3><p>{service.total_asistencias || 0} asistencias registradas</p></div></div>{service.departments.map((department) => <div className="service-department" key={department.departamento}><span>{department.departamento}</span><div className="progress"><i style={{ width: `${Number(service.total_asistencias) ? (Number(department.total_asistencias) / Number(service.total_asistencias)) * 100 : 0}%` }} /></div><b>{department.total_asistencias}</b><small>{department.empleados_usuarios} empleados</small></div>)}</article>)}</div></section><section className="panel insight-panel"><div className="insight-icon">✦</div><p className="eyebrow">LECTURA PARA LA DECISIÓN</p><h2>{services.length === 2 && Number(services[0].total_asistencias) !== Number(services[1].total_asistencias) ? `La demanda se inclina hacia ${Number(services[0].total_asistencias) >= Number(services[1].total_asistencias) ? services[0].servicio : services[1].servicio}` : 'La demanda está equilibrada'}</h2><p>Compara el porcentaje de empleados usuarios y los departamentos participantes antes de evaluar si conviene ampliar, ajustar o comunicar mejor la prestación.</p></section></>
}

function ServiceCard({ service, share }) { return <article className="panel service-card"><div className={`service-mark ${service.servicio === 'Masaje' ? 'massage' : 'physio'}`}>{service.servicio === 'Masaje' ? '✦' : '✚'}</div><p className="eyebrow">SERVICIO</p><h2>{service.servicio}</h2><div className="service-stat"><strong>{service.total_asistencias || 0}</strong><span>asistencias</span></div><div className="service-meta"><span><b>{service.empleados_usuarios || 0}</b> empleados usuarios</span><span><b>{service.departamentos_usuarios || 0}</b> departamentos</span><span><b>{share}%</b> del uso total</span></div></article> }
export default ServicesView
